### ISSUE TITLE
err StatusCodeError: [mapper_parsing_exception] failed to parse field [result] of type [text]

### ISSUE THREAD

**Issue by CrispyCB** [diogolmenezes/elastic-butler#10]
```
err StatusCodeError: [mapper_parsing_exception] failed to parse field [result] of type [text]
    at respond (/home/cebahnweg/Desktop/elk/elastic-butler/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/home/cebahnweg/Desktop/elk/elastic-butler/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/home/cebahnweg/Desktop/elk/elastic-butler/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/home/cebahnweg/Desktop/elk/elastic-butler/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  status: 400,
  displayName: 'BadRequest',
  message: '[mapper_parsing_exception] failed to parse field [result] of type [text]',
  path: '/elastic_butler_execution/execution',
  query: {},
  body: {
    error: {
      root_cause: [Array],
      type: 'mapper_parsing_exception',
      reason: 'failed to parse field [result] of type [text]',
      caused_by: [Object]
    },
    status: 400
  },
  statusCode: 400,
  response: `{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse field [result] of type [text]"}],"type":"mapper_parsing_exception","reason":"failed to parse field [result] of type [text]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:1064"}},"status":400}`,
  toString: [Function],
  toJSON: [Function]
}
```

I keep getting the above error whenever I run my Butler install. Any idea what could be causing it would be much-appreciated!

**Comment by diogolmenezes** [comment]
Hey ! You tried to run the https://github.com/diogolmenezes/elastic-butler#sandbox sample ?

**Comment by CrispyCB** [comment]
Yep - I was running it against the sandbox sample, yes.

**Comment by diogolmenezes** [comment]
I think you are having trouble with the index.

I suggest that you remove all sample index and try again.

 Curl -XDELETE localhost:9200/index_name
